### ISSUE TITLE
node.js version

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#1]
Udger could use a node.js version as well. Any thoughts on adding one?

**Comment by mallat** [comment]
I agree that Node.js version would be appropriate.We are currently planned. After some adjustment, it is possible to use this: https://github.com/GUI/uas-parser

**Comment by tiborb** [comment]
Maybe someone can add a node version.

**Comment by eviltik** [comment]
Done, you can close this ticket.

https://github.com/udger/udger-nodejs
