### ISSUE TITLE
Replace SQLite with PDO

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#10]
Replace new \SQLite3 with a more generic driver: PDO. 
http://php.net/manual/en/ref.pdo-sqlite.php

PDO is always available and no more composer check is needed.

**Comment by mallat** [comment]
It is not true that PDO_SQLITE is always available. It is an extension php_pdo_sqlite.
The extension used php_sqlite3 situation is the same. 
It is true that a wrapper PDO is general, but the data are sqlite3.

**Comment by tiborb** [comment]
I agree, but it's active by default. 
When not active it can be installed via pecl, the package is in alpha stage https://pecl.php.net/package/sqlite3.
When I try to install the alpha it crashed. IMHO it's not prod safe. That's why I suggest PDO.

**Comment by mallat** [comment]
PDO will be added, but not now. 
Preparing a new/expanded version of the data. Data will be available not only in sqlite.

**Comment by tiborb** [comment]
Sounds great, I am also using the current one for now. Refactoring the parser will me more safe now since we have tests.

**Comment by mallat** [comment]
You can contact me directly in the mail (jaroslavDOTmallatATgmail.com), I'd like to discuss next steps, please.
