### ISSUE TITLE
PSR logger

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#11]
Echoing from the parser class in dangerous. 
And the class should done one thing, and do it well, parsing agents.
Adding a PSR comptible logger would make the code more safe and easier to debug in large projects.

https://github.com/Seldaek/monolog

**Comment by tiborb** [comment]
Is this ticket rejected? Cheers

**Comment by mallat** [comment]
No

**Comment by tiborb** [comment]
Alright, then it might be better if we leave it open, just to have a todo list.
