### ISSUE TITLE
Composer file and Packagist

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#2]
Adding a https://getcomposer.org/ file would make it more easy to manage the parser in a project.
It could be published to https://packagist.org/ too.

**Comment by tiborb** [comment]
@mallat  Publishing to Packagist can only be done by the (github) project owner.

**Comment by mallat** [comment]
Published -- https://packagist.org/packages/udger/udger-php

And thank you very much.

**Comment by tiborb** [comment]
Awsome! Can you also add a tag? 
Because my Composer unfortunately does not find a stable version. 
See: https://github.com/udger/udger-php/releases

Thanks,
Tibor

**Comment by mallat** [comment]
It works now?

**Comment by tiborb** [comment]
Installing the dev-master version works, 
the 1.3.0 version hasn't been picked up by packagist yet, maybe it needs a couple more minutes.

**Comment by mallat** [comment]
Set set up the GitHub Service Hook for Packagist.

**Comment by tiborb** [comment]
+1
