### ISSUE TITLE
Add a proxy option

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#28]
Add a proxy option when performing a datefile update.

http://www.higherpass.com/php/tutorials/Using-Curl-To-Query-Remote-Servers/3/

**Comment by mallat** [comment]
The parser for the third version of the data (currently in dev) update is launched. To update the data will be used updater (https://udger.com/support/documentation/?doc=62).. Support proxy is a good idea.

**Comment by mallat** [comment]
Yes correct. Likewise, the update has been removed from other libraries.

**Comment by tiborb** [comment]
will be supported by the standalone updater
