### ISSUE TITLE
parser v3

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#30]
Meta ticket for TODOs to finalize the parser for the v3 .dat files.

@mallat could you extend the TODO list here? I would offer dev support.

**Comment by mallat** [comment]
Parser is OK at 99%
it is a need
- on windows does not work properly ip2long
- composer  support
- examples
- tests

**Comment by tiborb** [comment]
Thank you, what is wrong with ip2long on windows?

**Comment by mallat** [comment]
example:
print_r( ip2long('212.129.32.1') );
- linux: 3565232129
- win: -729735167

a possible solution (but must check .. I do not know if it's OK for all IP addresses):
print_r( sprintf('%u', ip2long('212.129.32.1')) );
- linux: 3565232129
- win: 3565232129

**Comment by tiborb** [comment]
I have the same fix in prod. See this article as well: http://stackoverflow.com/questions/3062843/php-ip2long-returning-negative-val

The proposed solution is fine: sprintf('%u', ip2long('<IP>'));

**Comment by tiborb** [comment]
The tests need a v3 .dat file fixture as well. Do you have a small file that can be used for testing?

**Comment by mallat** [comment]
yes ... https://github.com/udger/test-data/tree/master/data_v3

**Comment by tiborb** [comment]
:+1:

**Comment by tiborb** [comment]
I am working on the v3 (dev) branch. If the downloader (bash) is standalone, I will remove it from the v3 parser code. What do you think?

**Comment by mallat** [comment]
I absolutely agree.

**Comment by tiborb** [comment]
manual_update_data.php can also be removed

**Comment by mallat** [comment]
yes

**Comment by tiborb** [comment]
The changes have been pushed to the dev branch, have a look.
When merging into master, I would squash the commits to have a better overview.

**Comment by mallat** [comment]
I made a few changes there .... Anyway, thank you
