### ISSUE TITLE
 Error: Call to a member function fetchArray() on boolean

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#34]
PHP Warning:  SQLite3::query(): Unable to prepare statement: 1, near "S": syntax error in vendor/udger/udger-php/src/Parser.php on line 252
PHP Fatal error:  Call to a member function fetchArray() on boolean in vendor/udger/udger-php/src/Parser.php on line 254

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Error: Call to a member function fetchArray() on boolean

**Comment by mallat** [comment]
fixed
