### ISSUE TITLE
SQL parameterization breaks for several device codes

### ISSUE THREAD

**Issue by joewreschnig** [udger/udger-php#36]
The `udger_devicename_list` table contains several entries with an unescaped `'` in their code, so constructing the query on Parser.php:438 results in invalid SQL. Some examples:

```sql
INSERT INTO "udger_devicename_list" VALUES(1,33,'9.4'' FFF','9.4'' FFF');
INSERT INTO "udger_devicename_list" VALUES(1,15,'ALCATEL OT-5020A M''POP','One Touch M''Pop');
INSERT INTO "udger_devicename_list" VALUES(1,453,'eZee''Tab1001','eZee''Tab 1001');
```

I don't know if you'd prefer to solve this by removing `'` as seems to be done for codes in other tables, or by preparing and parameterizing the query. (Or maybe both.)

**Comment by mallat** [comment]
fixed - https://github.com/udger/udger-php/commit/2899965ba664798bc64ce41d319d5c39c7f4f71c
