### ISSUE TITLE
Add update data command

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#8]
Downloading the current data file must be done manually at the moment.
Adding an update command would be really helpful.

It should:
- check the validity of the access key
- check the installed version
- install a newer version if available at udger.com
- the data file path should be configurable

Cheers,
Tibor

**Comment by mallat** [comment]
Hi Tibor.
- The path to the data file is adjustable see .. $parser->SetDataDir
- The data file is downloaded by comparing locally stored version and the version available on the server data.udger.com  ... https://github.com/udger/udger-php/blob/master/src/Parser.php#L619
- I am fundamentally opposed to automatically update the library, I do not like

**Comment by tiborb** [comment]
I am also against fully automatic updates. 
But as understood, right now, I have have to curl down the .dat file from http://data.udger.com/<key>/udgerdb.dat and place it in a dir where the parser can find it.

Or is there a more elegant way at the moment?

Tibor

**Comment by mallat** [comment]
And what was the reason for manual download?
Jaroslav

**Comment by tiborb** [comment]
The lack of a known alternative.
How do you update the dat files?

**Comment by mallat** [comment]
curl :) .. OK, then add the method updateData()

**Comment by tiborb** [comment]
I added the updateData method to the parser and a test to cover it.

The main advantage is that in some cases 
it is not wanted that the parser automatically downloads a new .dat file. 

So the updateData() can be called periodically (or by a cron) to perform an update.
Auto updates can be disabled completely as well, any only the .dat file placed in the cache directory is being used.

See #12 

Cheers,
Tibor

**Comment by mallat** [comment]
Good job, thank you very much

**Comment by tiborb** [comment]
Thank you too.
Can I suggest leaving the 'accepted' change tickets open until resolved? 
I would be more clear what is tom be done ;)
