### ISSUE TITLE
Extend tests coverage

### ISSUE THREAD

**Issue by tiborb** [udger/udger-php#9]
Add codeception or phpunit tests, and Travis integration.

**Comment by mallat** [comment]
PHPUnit will be added in a future release. Travis CI integration probably not.

**Comment by tiborb** [comment]
I started it just now. PR will follow soon

**Comment by tiborb** [comment]
A .dat file as a functional test fixture would be really helpful, with only 2-3 ua entries.
Do you save one at hand?

Thanks,
Tibor

**Comment by mallat** [comment]
example sqlite db
[udgerdb.zip](https://github.com/udger/udger-php/files/103425/udgerdb.zip)
